---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "yarn.lock"}}
            - v1-yarn-{{checksum ".circleci/config.yml"}}
      - run: yarn
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run:
          name: "Test Suite"
          command: yarn jest --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results: &store_test_results
          path: reports/junit
  node-8:
    <<: *test
    docker:
      - image: node:8
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/cli/.npmrc
      - run:
          name: Publish package
          command: yarn publish
      - save_cache:
          key: v1-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "ssmenv":
    jobs:
      - node-latest:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - node-8:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - release:
          context: org-global
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - node-latest
            - node-8
