---
version: 2
jobs:
  node-latest-env: &test_env
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
    steps:
      - checkout
      # This works because "A key is searched against existing keys as a prefix."
      - restore_cache: &restore_cache_global
          key: v2-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
      - restore_cache: &restore_cache_env
          key: v2-{{checksum ".circleci/config.yml"}}-{{checksum "packages/ssmenv/yarn.lock"}}
      - run: &install_global
          name: "Install global Dependencies"
          command: yarn
      - run: &install_ssmenv
          name: "Install ssmenv Dependencies"
          command: yarn
          working_directory: ~/cli/packages/ssmenv
      - run: &lerna_bootstrap
          name: "Lerna Bootstrap"
          command: yarn lerna bootstrap
      - save_cache: &save_cache_global
          key: v2-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}-{{ .BuildNum }}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
      - save_cache: &save_cache_env
          key: v2-{{checksum ".circleci/config.yml"}}-{{checksum "packages/ssmenv/yarn.lock"}}-{{ .BuildNum }}
          paths:
            - ~/cli/packages/ssmenv/node_modules
      - run: &run_mkreports
          command: mkdir -p reports/junit
          working_directory: ~/cli/packages/ssmenv
      - run: &run_lint
          name: "Linter"
          command: yarn tslint -p . -t stylish --format junit -o reports/junit/js-lint-results.xml
          working_directory: ~/cli/packages/ssmenv
      - run: &run_jest
          name: "Test Suite"
          command: yarn jest --ci --testResultsProcessor="jest-junit"
          working_directory: ~/cli/packages/ssmenv
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: packages/ssmenv/reports/junit
  node-8-env:
    <<: *test_env
    docker:
      - image: node:8
  release-env:
    <<: *test_env
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache_global
      - restore_cache: *restore_cache_env
      - run: *install_global
      - run: *install_ssmenv
      - run: *lerna_bootstrap
      - run: &run_auth
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          working_directory: ~/cli/packages/ssmenv
      - run: &run_publish
          name: Publish package
          command: |
            VERSION=$(echo $CIRCLE_TAG | cut -c2-)
            yarn publish --new-version="${VERSION}"
          working_directory: ~/cli/packages/ssmenv
      - save_cache: *save_cache_global
      - save_cache: *save_cache_env
  node-latest-cli: &test_cli
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
    steps:
      - checkout
      # This works because "A key is searched against existing keys as a prefix."
      - restore_cache: *restore_cache_global
      - restore_cache: &restore_cache_cli
          key: v2-{{checksum ".circleci/config.yml"}}-{{checksum "packages/ssmenv-cli/yarn.lock"}}
      - run: *install_global
      - run: *install_ssmenv
          working_directory: ~/cli/packages/ssmenv-cli
      - run: *lerna_bootstrap
      - save_cache: *save_cache_global
      - save_cache: &save_cache_cli
          key: v2-{{checksum ".circleci/config.yml"}}-{{checksum "packages/ssmenv-cli/yarn.lock"}}-{{ .BuildNum }}
          paths:
            - ~/cli/packages/ssmenv-cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
      - run:
          command: ./bin/run --version
          working_directory: ~/cli/packages/ssmenv-cli
      - run:
          command: ./bin/run --help
          working_directory: ~/cli/packages/ssmenv-cli
      - run: *run_mkreports
          working_directory: ~/cli/packages/ssmenv-cli
      - run: *run_lint
          working_directory: ~/cli/packages/ssmenv-cli
      - run: *run_jest
          working_directory: ~/cli/packages/ssmenv-cli
      - store_test_results:
          path: packages/ssmenv-cli/reports/junit
  node-8-cli:
    <<: *test_cli
    docker:
      - image: node:8
  release-cli:
    <<: *test_cli
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache_global
      - restore_cache: *restore_cache_cli
      - run: *install_global
      - run: *install_ssmenv
          working_directory: ~/cli/packages/ssmenv-cli
      - run: *lerna_bootstrap
      - run: *run_auth
          working_directory: ~/cli/packages/ssmenv-cli
      - run: *run_publish
          working_directory: ~/cli/packages/ssmenv-cli
      - save_cache: *save_cache_global
      - save_cache: *save_cache_cli

workflows:
  version: 2
  "ssmenv":
    jobs:
      - node-latest-env: &tag_filters
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - node-8-env: *tag_filters
      - release-env:
          context: org-global
          filters: &tag_branch_filters
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - node-latest-env
            - node-8-env
  "ssmenv-cli":
    jobs:
      - node-latest-cli: *tag_filters
      - node-8-cli: *tag_filters
      - release-cli:
          context: org-global
          filters: *tag_branch_filters
          requires:
            - node-latest-cli
            - node-8-cli
