---
version: 2
jobs:
  node-latest-env: &job_env
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
    steps:
      - checkout
      # This works because "A key is searched against existing keys as a prefix."
      - restore_cache: &restore_workspaces
          key: v3-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
      - run: &install_workspaces
          name: "Install Workspace Dependencies"
          command: yarn
      - run: &lerna_bootstrap
          name: "Lerna Bootstrap"
          command: |
            yarn lerna bootstrap
            yarn lerna run prepare
      - save_cache: &save_workspaces
          key: v3-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}-{{ .BuildNum }}
          paths:
            - ~/cli/node_modules
            - ~/cli/packages/ssmenv/node_modules
            - ~/cli/packages/ssmenv-cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn
      - run: &run_mkreports
          command: mkdir -p reports/junit
          working_directory: ~/cli/packages/ssmenv
      - run: &run_jest
          name: "Test Suite"
          command: yarn run test --testResultsProcessor="jest-junit"
          working_directory: ~/cli/packages/ssmenv
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: packages/ssmenv/reports/junit
  node-8-env:
    <<: *job_env
    docker:
      - image: node:8
  node-latest-cli: &job_cli
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
    steps:
      - checkout
      # This works because "A key is searched against existing keys as a prefix."
      - restore_cache: *restore_workspaces
      - run: *install_workspaces
      - run: *lerna_bootstrap
      - save_cache: *save_workspaces
      - run:
          command: ./bin/run --version
          working_directory: ~/cli/packages/ssmenv-cli
      - run:
          command: ./bin/run --help
          working_directory: ~/cli/packages/ssmenv-cli
      - run:
          <<: *run_mkreports
          working_directory: ~/cli/packages/ssmenv-cli
      - run:
          <<: *run_jest
          working_directory: ~/cli/packages/ssmenv-cli
      - store_test_results:
          path: packages/ssmenv-cli/reports/junit
  node-8-cli:
    <<: *job_cli
    docker:
      - image: node:8
  release:
    <<: *job_env
    docker:
      - image: node:8
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_workspaces
      - run: *install_workspaces
      - run: *lerna_bootstrap
      - run:
          name: Authenticate with registry
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            cp .npmrc packages/ssmenv
            cp .npmrc packages/ssmenv-cli
      - run:
          name: "Run Lerna Publish"
          command: |
            VERSION=$(echo $CIRCLE_TAG | cut -c2-)
            yarn lerna publish --repo-version="${VERSION}" --skip-git --yes
          working_directory: ~/cli

workflows:
  version: 2
  "ssmenv":
    jobs:
      - node-latest-env: &tag_filters
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - node-latest-cli: *tag_filters
      - node-8-env: *tag_filters
      - node-8-cli: *tag_filters
      - release:
          context: org-global
          filters: &tag_branch_filters
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - node-latest-env
            - node-latest-cli
            - node-8-env
            - node-8-cli
