---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    environment:
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-yarn-{{checksum ".circleci/config.yml"}}-{{ checksum "packages/ssmenv/yarn.lock"}}
            - v1-yarn-{{checksum ".circleci/config.yml"}}
      - run:
          command: yarn
          working_directory: ~/cli/packages/ssmenv
      - run:
          command: ./bin/run --version
          working_directory: ~/cli/packages/ssmenv
      - run:
          command: ./bin/run --help
          working_directory: ~/cli/packages/ssmenv
      - run:
          command: mkdir -p reports/junit
          working_directory: ~/cli/packages/ssmenv
      - run:
          name: "Linter"
          command: yarn tslint -p . -t stylish --format junit -o reports/junit/js-lint-results.xml
          working_directory: ~/cli/packages/ssmenv
      - run:
          name: "Test Suite"
          command: yarn jest --ci --testResultsProcessor="jest-junit"
          working_directory: ~/cli/packages/ssmenv
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results: &store_test_results
          path: packages/ssmenv/reports/junit
  node-8:
    <<: *test
    docker:
      - image: node:8
  release:
    <<: *test
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: *restore_cache
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/cli/.npmrc
          working_directory: ~/cli/packages/ssmenv
      - run:
          name: Publish package
          command: |
            VERSION=$(echo $CIRCLE_TAG | cut -c2-)
            yarn publish --new-version="${VERSION}"
          working_directory: ~/cli/packages/ssmenv
      - save_cache:
          key: v1-yarn-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/packages/ssmenv/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "ssmenv":
    jobs:
      - node-latest:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - node-8:
          context: org-global
          filters:
            tags:
              only: /^v.*/
      - release:
          context: org-global
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - node-latest
            - node-8
